### ISSUE TITLE
pdo

### ISSUE THREAD

**Issue by Firestorm-Graphics** [mudmin/UserSpice4#1]
hey great script, i would have posted the following question on your forums but I'm getting a forbidden notice when trying to register.

Has anyone come across this error "Fatal error: Class 'PDO' not found in /****_/**_***/public_html/userspice/users/classes/DB.php on line 26" ? the script was working fine yesterday but this morning it threw this error. I've only modded the navigation and header html along with css. any thoughts ? PDO module is installed on my server

**Comment by mudmin** [comment]
Btw, I fixed the forbidden issue.  That was a spam prevention feature that was overzealous. Let me know if you still can't register. 

A few things to check... 
1. try renaming your php.ini or .htaccess to something different and see if the error goes away.
2. Try running a page with the code ... debug(PDO::getAvailableDrivers()); and see what the output is.
3. If you have the ability to reboot your server, you might want to try that. 
4. You could also be having some sort of namespace issue.  
5. Also try adding the line phpinfo(); to one of your pages and see what it says about pdo.  Let me know how I can help.

**Comment by Firestorm-Graphics** [comment]
thanks alot for your help, shared server unfortunately but after php info it looks like setting php to 5.6 in cpanel isnt taking effect so server looks to be runing 5.4 :( my provider is working on it as we speak :)
