### ISSUE TITLE
undefined variable $master_account

### ISSUE THREAD

**Issue by micbuh** [mudmin/UserSpice4#11]
Hello!

Due to wrong page permissions, I ran into an php error: 
  Undefined variable: master_account in /var/www/clients/client1/web11/web/users/helpers/us_helpers.php on line 431

$master_account is indeed not defined anywhere in the code.

egrep -R master_account *
users/helpers/us_helpers.php:		}elseif ($user->data()->id == $master_account){ //Grant access if master user

Regards, Michael

**Comment by mudmin** [comment]
Did you delete the user with an id of 1?

I'm sorry for the slow response. I answer questions much faster on userspice.com

**Comment by micbuh** [comment]
no, id 1 admin is still in use.
anyhow, I would expect that $master_account is written somewhere else, but it's not.
refer search for variable: https://github.com/mudmin/UserSpice4/search?utf8=%E2%9C%93&q=%24master_account

**Comment by mudmin** [comment]
I have zero idea how that hasn't caused anyone else problems.  It used to be that the master account had the id of 1 and that was defined but somehow that's gotten taken away.  

I just did a lot of research and I used to define it in the old config.php in UserSpice 3 and it must have been removed in version 4.  It kind of makes sense to be able to define a user with master access so they don't get locked out of anything by accident (like the admin panel), but I'm not using that logic.  I guess temporarily I would stick it $master_account = 1; at the top of usersc/includes/custom_functions.php while I work out what to do with this.

**Comment by lukeshep** [comment]
Hi there - if it helps anyone searching I had similar issue (v4) I made it go away by updating the access on the manage pages access screens, the page in question needed two entries for some reason, one with and one without a preceding "/" (a couple of pages in the project root directory rather than usersc)
