### ISSUE TITLE
Copyright message with apostrophe causes error

### ISSUE THREAD

**Issue by lezsakdomi** [mudmin/UserSpice4#12]
The copyright message (given during install) becomes not backslashed. It's written out raw, and results an "Unexpected T_STRING at users/init.php" on homepage, if I close the apostrophe on install interface

**Comment by mudmin** [comment]
You have to escape the string with a \ so it would be Lezsakdomi\'s UserSpice.
I probably should do that automatically. Sorry about that.  Feel free to ask any questions at userspice.com
