### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by MichaelSmi** [mudmin/UserSpice4#13]
When loading UserSpice4 I get this error in **users/init.php** on line 26:
`AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected end of file, expecting ')' in /var/www/vhosts/example.org/htdocs/vendor/userspice/users/init.php on line 26\n'`
BTW is there a new walkthrough for hacking UserSpice4 using a custom frontend? I'd love to use UserSpice4 together with AdminLTE!

**Comment by Firestorm-Graphics** [comment]
if thats after installation of userspice then it maybe didn't install correctly, try reinstalling, checking file permissions beforehand

**Comment by Firestorm-Graphics** [comment]
This is what i suspect is in your init.php, this is where it starts, after install it gets the rest written to it, mine has apron 96 line total.

`<?php
session_start();

$abs_us_root=$_SERVER['DOCUMENT_ROOT'];

$self_path=explode("/", $_SERVER['PHP_SELF']);
$self_path_length=count($self_path);
$file_found=FALSE;

for($i = 1; $i < $self_path_length; $i++){
	array_splice($self_path, $self_path_length-$i, $i);
	$us_url_root=implode("/",$self_path)."/";
	
	if (file_exists($abs_us_root.$us_url_root.'z_us_root.php')){
		$file_found=TRUE;
		break;
	}else{
		$file_found=FALSE;
	}
}

require_once $abs_us_root.$us_url_root.'users/helpers/helpers.php';

// Set config
$GLOBALS['config'] = array(
	'mysql'      => array(`

from array(  your server credentials get written
