### ISSUE TITLE
Notice:  Undefined variable: master_account in

### ISSUE THREAD

**Issue by nessinits** [mudmin/UserSpice4#16]
I get the following in us_helper.php

<br />
<b>Notice</b>:  Undefined variable: master_account in <b>/home/plob347868/domains/uzbc.nl/public_html/site/workload/users/helpers/us_helpers.php</b> on line <b>788</b><br />
<br />
<b>Warning</b>:  in_array() expects parameter 2 to be array, null given in <b>/home/plob347868/domains/uzbc.nl/public_html/site/workload/users/helpers/us_helpers.php</b> on line <b>788</b><br />

The $master_account is (normally) defined in init.php and is included. Don't know what's wrong, but I think it's a bug.

The value of $master_account is 1 and that account exists.

**Comment by mudmin** [comment]
We're working on this and discussing it in the userspice forums. I'm not exactly sure what pages are throwing the error. As a temp fix, you can define $master_account=[1]; in that function of us_helpers.

**Comment by Firestorm-Graphics** [comment]
you have to do global $master_account; in a function i do believe.

**Comment by mlingelbach** [comment]
Hi,

I have the same issue, but no solution for it. Can you provide please your changes so that it works?

Thanks,
Markus

**Comment by Brandin** [comment]
@mlingelbach This will be resolved in 4.4. As @Firestorm-Graphics mentioned, you just need to global $master_account in the function.

**Comment by mlingelbach** [comment]
Yes, I did it, but when I'm logged in as an normal user, I have still the ERR_TOO_MANY_REDIRECTS - Error

In the logs are no errors :( The last are: PHP Warning:  in_array() expects parameter 2 to be array, null given ....

I did it for the securePage function
