### ISSUE TITLE
stripe ?

### ISSUE THREAD

**Issue by Firestorm-Graphics** [mudmin/UserSpice4#2]
is stripe integrated as i found reference to it in init? if it is whats its intended usage in vanilla user spice ?

**Comment by mudmin** [comment]
Some of the hooks are still in there. The original plan was to offer the option for paid memberships when I started version 4.0.  There wasn't any feedback for this need, so I didn't build it out.  It's just as easy (probably easier) to let people sign up and then pay to get their membership bumped up to a different level. There is so much going on during the registration process that it just added complexity.

**Comment by Firestorm-Graphics** [comment]
oh i see, makes sense now :)
