### ISSUE TITLE
[Bug] Force password reset on manual creation

### ISSUE THREAD

**Issue by Nate-DoggUK** [mudmin/UserSpice4#21]
Hi there,

I have set up UserSpice and we want users to set their own password, however when a user receives the signup message with the "Set password" link - you get taken to a page where you can set your new password, except no matter what you enter as the new password you get an error: "Oops...something went wrong, maybe an old reset link you clicked on. Click below to try again".

The user must then manually request a password reset e-mail, which then accepts their new password.

Hopefully you can resolve the issue with manual account creation set password link.

**Comment by Brandin** [comment]
Hi Nate,

The links generated by the Manual Account Creation expire based on the time set in the Admin Dashboard, default is 24 hours. If you use the link after this period, it will not work and a new one will be required.

Thanks,
Brandin.

**Comment by Nate-DoggUK** [comment]
Hi Brandin,

I'm clicking the link within minutes of their account creation, I have also extended the time to be 72 hours rather than 24 with no luck. :(

Just as a further test, I increased the "Registration Vericode Expiry (in hours)" to be 9,999 to avoid any timezone issues - although I did set London during the set up. No joy so far.

Kind regards,
Nathan

**Comment by Brandin** [comment]
Hi Nathan,

Please create a user and check the Database directly to compare the time to your current PHP time which you can get by doing <?=dump(date("Y-m-d H:i:s")?>

Thanks,
Brandin.

**Comment by Nate-DoggUK** [comment]
Hi Brandin,

Thanks for the reply.
I have created a new user and pulled their creation time from the database which is: 2018-07-10 18:51:10
I have also run echo'ed the date and time using PHP which returned the following: 2018/07/10 17:51:34

While there is an hour different due to the daylight saving it's still within the e-mail verification time frame.

Could I also check, when I create a user - is it meant to log me in as them? Unless that's what is causing the problem, when I create a user it changes my username at the top right to theirs and puts me on the account page with the red "You must change your password" text. Therefore I have to log out as them and back in as myself.

Edit: I have just seen that the "vericode_expiry" in the database for the account matches its last login time: 2018-07-10 18:51:11 - would that be why?

Kind regards,
Nathan

**Comment by Brandin** [comment]
This seems to happen sometimes-and sometimes not. I think its an ongoing bug we've never been able to solve. Possibly something in the during_user_creation or the custom_login_script causing this behavior (the login on creation).

It is possible this column is getting broken when a user signs in. And now that I'm testing that-that is exactly the problem. Currently that column is set as a timestamp which creates an automatic ON UPDATE CURRENT_TIMESTAMP() attribute which means anytime that row is updated (including on login) it updates that timestamp to the current timestamp.

Please go into phpMyAdmin, into the users table, and edit the column vericode_expiry to be a datetime column with no attribute.

Thanks,
Brandin.

**Comment by Nate-DoggUK** [comment]
Hi Brandin,

I have updated the "vericode_expiry" column to be DATETIME with no default and removing the attributes.
This has fixed the issue I have been having where users cannot set their initial password after manual creation

Thank you for your help.

Kind regards,
Nathan

**Comment by Nate-DoggUK** [comment]
Hi Brandin,

Thanks again for you reply, I have now disabled the auto log in as the user you just created via the during_user_creation.php script as I didn't have e-mail verification turned on.

Kind regards,
Nathan

**Comment by Brandin** [comment]
Thanks for the notes Nathan, I've added these to our bug reporter to fix.

Feel free to register at our forums, join our Discord and visit our Bug Tracker:
https://userspice.com/forums/
https://discord.gg/Zy5QfFE
https://userspice.com/bugs/

Brandin.
