### ISSUE TITLE
PHP warning when trying to test database connection during install

### ISSUE THREAD

**Issue by jlcfly** [mudmin/UserSpice4#26]
If PHP is configured to show all errors, a PHP warning will appear when trying to test the database connection in step2.php. Recommend changing line 202 from:

`$link = mysqli_connect($dbh, $dbu, $dbp, $dbn);`

To:

`$link = @mysqli_connect($dbh, $dbu, $dbp, $dbn);`

The @ will suppress the warning, allowing the code to continue.

**Comment by Brandin** [comment]
Thank you, we will work on patching this ASAP.

https://userspice.com/bugs/usersc/issue_detail.php?id=616
