### ISSUE TITLE
Extra fclose in step2.php

### ISSUE THREAD

**Issue by jlcfly** [mudmin/UserSpice4#27]
step2.php has an extra fclose($fh) on line 162, which throws a PHP warning. This would be seen if all errors and warnings are shown. By the time the code gets here, $fh is no longer available as fclose already ran on line 159. The subsequent file_put_contents doesn't utilize a file handle.

**Comment by Brandin** [comment]
Thank you for your report, we will work on this.

https://userspice.com/bugs/usersc/issue_detail.php?id=617

**Comment by Brandin** [comment]
Moved to tracker
