### ISSUE TITLE
Languageswitcher problem in IE and Edge

### ISSUE THREAD

**Issue by kernig** [mudmin/UserSpice4#28]
Hi @mudmin, @brandinarsenault ,
there seems to be a problem with the languageswitcher in userspice.
In https://github.com/mudmin/UserSpice4/blob/master/users/helpers/us_helpers.php on line 1712 it skips every $_POST value except the third. The order of var_dump($_POST) is "your_token, language_selector, de-DE_x, de-DE_y, csrf" which makes "de-DE_x" the third value. In Internet Explorer and Edge the order is as follows "your_token, language_selector, csrf, de-DE_x, de-DE_y". The post sending order was verified via fiddler https://www.telerik.com/download/fiddler. I replaced "if(($count != 3))" with "if(($count != 4))" which works in my case, cause it gets de-DE_x on FF and de-DE_y in IE and Edge. 
There also is no value in the token var(csrf) on line 1747 and two alt attributes on 1743.
I don't know if you are using the value and not just the name of the *_x and *_y postvars, but there could be another problem in IE/Edge if you hit the flag with your return key - https://stackoverflow.com/questions/22004789/if-isset-post-not-working-for-internet-explorer/22005299#22005299

Thank you for providing this great framework!

**Comment by mudmin** [comment]
I might need some more clarification. Are you on our discord server?

**Comment by Brandin** [comment]
Closing issue, please send a request in Discord if this remains problematic. Edge is moving to chromium based so this may be a non-important issue.
